name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - awkward >=2.4.0
  - hist-base
  - vector
  - numpy
  - matplotlib-base>=3.8.0
  - mplhep
  - uproot-base >=5.0.12
