name: binder
channels:
  - conda-forge
dependencies:
  - python =3.10
  - jupyterlab
  # Kernel
  - awkward >=2.4.0
  - hist-base
  - vector
  - numpy
  - matplotlib-base
  - mplhep
  - uproot-base >=5.0.12
