name: binder
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab
  - jupyterlab-myst >=2.1.0
  - pip:
      - ./extern/jupyterlab_deck-0.4.0a0-py3-none-any.whl
  # Kernel
  - awkward >=2.4.0
  - hist-base
  - vector
  - numpy
  - matplotlib-base
  - mplhep
  - uproot-base >=5.0.12
